### ISSUE TITLE
src/demo fail to build

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#11]
Testing src/demo by running src/demo/demo.sh fail due to missing options `-std=c99 -D_Nullable= -D_Nonnull=` adding then works with gcc/clang.
```
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

O="../out"
CQL="${O}/cql"

${CQL} --in demo.sql --cg ${O}/demo.h ${O}/demo.c --generate_copy
cc  -std=c99 -D_Nullable= -D_Nonnull= -g -I.. -I${O} -o ${O}/demo ${O}/demo.c ../cqlrt.c demo_client.c -lsqlite3
${O}/demo
echo "SUCCESS"
```

**Comment by ricomariani** [comment]
This needs to get treatment in the Makefile so that we build it with the right options.  It's a bit of an orphan stepchild.

The easiest way to fix this is to make "demo" a target in the makefile and use the Makefile's existing mechanism do the flags management.  This is exactly what we did with "tester"

**Comment by ricomariani** [comment]
Actually you don't need to do this.  I'm making the change right now... It's tiny.

**Comment by ricomariani** [comment]
I commit the change to use the Makefile to get the right CFLAGS
