### ISSUE TITLE
Objc-runtime: Consider adding an inline helper function to create a CGS_X_fetch_results

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#110]
It seems to me that most users of the Objective-C runtime (by which I mean users calling from Obj-C, since the Swift runtme wraps this code in generated code) are going to do this dance:

```
    todo_tasks_result_set_ref result_set_ref;
    rc = todo_tasks_fetch_results(db, &result_set_ref);
    if (rc != SQLITE_OK) {
      printf("error: %d\n", rc);
      exit(2);
    }
    CGS_todo_tasks *rs = CGS_todo_tasks_from_todo_tasks(result_set_ref);
    cql_release(result_set_ref);  // objective C is now in control of the refs
```

All this code could be in the objc.h header in an inline function, something like:

```
static inline int32 CGS_todo_tasks_fetch_results(CGS_todo_tasks **resultSet) {
...
}
```

It would be used like this:

```
CGS_todo_tasks * rs;
    rc = CGS_todo_tasks_fetch_results(db, &result_set_ref);
    if (rc != SQLITE_OK) {
      printf("error: %d\n", rc);
      exit(2);
    }
```

**Comment by ricomariani** [comment]
This is very doable.  I'm sure I know why it wasn't done before.  It requires complex signatures which means cg_objc has to be more wired into the C codegen.  But it's just an inline function that forwards at the end of the day.

**Comment by ricomariani** [comment]
I have a diff set to land for this.  It's ready for review now.  Maybe later tonight or tomorrow.

**Comment by ricomariani** [comment]
Well sigh... my diff is inadequate, in fact I've missed the main problem here entirely. 

It turns out that in order to reasonably do this you also have to be willing to convert all the args from say NSString * to CFStringRef.  This turns out to be a lot more code and I'm not sure it's even worth the grief at this point.

**Comment by jackpal** [comment]
Sorry to hear that it didn't pan out. Thanks very much for investigating!

**Comment by ricomariani** [comment]
I think I can save it but it's a good bit more work than I originally thought.  I just missed the whole arg mismatch issue...
________________________________

**Comment by ricomariani** [comment]
So I did yet more work on this and ultimately I ended up abandoning my diffs.  The trouble is that the contract for procs is fairly complicated and creating yet a different contract and a full bijection between them ends up being a ton of code for fairly little value.

The nail in the coffin is that there are in/out/inout args and so you have to be ready to convert in both directions to the objc type.  This ends up being a ton of code but importantly it forces the objc system to be in bed with the c system and a single result_type data structure isn't enough to capture the knowledge.  You can sort of make it work if you use only the C types in your arguments because those you can pass through but then the only thing you save is that you don't have to do the cql_release(result_set_ref) dance.  But if you try to do more, like use `NSNumber *` for nullable integers like we do in the getters then you end up with a big ton of code that does very little.

I'm beginning to see the wisdom of the original authors position that they only wrap the result set, it gives a lot of value for the effort/complexity.

**Comment by ricomariani** [comment]
To make the above sort of work I had to do this horrible thing of temporarily changing "rt" to point to the C result type and then changing it back and even then I only got a thin wrapper.  To do this I had to fork a ton of code from cg_c.c and all of this to save one release just didn't seem worth it.  Which is too bad because I kind of like this idea but really we need to rethink how we do these at all.

I guess the other thing in the back of mind is that if I was doing this again -- I wouldn't.  I would just let people make their own using python and the JSON which probably ends up being less code and then you can do whatever conversions you like rather than living with ours.  Maybe a sample or two and that would be that.  The `--rt java code` which you haven't looked at is more plagued with these sorts of problems because there is no toll-free-bridging possible.

**Comment by jackpal** [comment]
Well, the downside of leaving the runtime implementation up to the client is that it raises the bar for people evaluating the technology. Because they will have to commit to a few weeks of development before they can get a demo working. I guess you can get around that with testimonials and case studies. Or perhaps some open-source project will adopt CG-SQL and then open-source their runtime.

I also worry that toll-free-bridging C<-->Obj-C interop is becoming a lost art in these use-Swift-for-everything days. If you don't provide a decent example runtime, it may be that no user will figure it out on their own.

**Comment by ricomariani** [comment]
I’m actually tempted to write the entire –rt objc as a python sample using the JSON to make it easier to do this stuff.  This is much more appealing than continuing to invest in code I wish we hadn’t written.  But the JSON didn’t exist at the time.  The Java is even worse.

But you’re 100% right.  Many people won’t even try to adopt it because just C bindings isn’t interesting to them.  More samples are important.

So much to do, so little time 😃



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ricomariani** [comment]
OK I've opened a task to consider doing the python work for objc which I think is interesting.  The rest of what is here is just never gonna happen on this plan so I'm gonna go ahead and close this issue.
