### ISSUE TITLE
demo_todo.sql bug, and cg-sql language question: should mixed int / long operations warn?

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#114]
I notice a bug in the todo sample app:

https://github.com/facebookincubator/CG-SQL/blob/main/sources/cqlrt_cf/demo_todo.sql

```sql
-- updates a given task by rowid
create proc todo_setdone_(rowid_ integer not null, done_ bool not null)
begin
  update tasks set done = done_ where rowid == rowid_;
end;

-- deletes a given task by rowid
create proc todo_delete(rowid_ integer not null)
begin
  delete from tasks where rowid == rowid_;
end;
```
In sqlite `rowid` is a `long`, so this code should be:

```sql
-- updates a given task by rowid
create proc todo_setdone_(rowid_ long not null, done_ bool not null)
begin
  update tasks set done = done_ where rowid == rowid_;
end;

-- deletes a given task by rowid
create proc todo_delete(rowid_ long not null)
begin
  delete from tasks where rowid == rowid_;
end;
```

The bug is easy to fix once we realize what it is, but I wonder if cg-sql should warn or even error on mixed int-long operations.

**Comment by ricomariani** [comment]
The trouble here is that int promotes to long...  It isn't even unreasonable to say "look my db only will have 200 rows or something, so I'm keeping my external rowids small".  long->int will give you a warning but not the other way around.

In some sense, the code as it was written wasn't wrong.  I noticed the difference right away but I assumed you knew it was fine because who are we kidding anyway around rowids > 4G.

In general you don't want to make

"where some_long_thing == a_small_number"  an error...

SQLite itself is even more loose than this.
