### ISSUE TITLE
cqlrt: Would it be worth adding a prepared statement cache?

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#115]
As far as I can tell, the current cqlrt implementation doesn't cache any prepared statements. Would adding a cache benefit apps that make repeated queries?

**Comment by ricomariani** [comment]
As it happens cqlrt can in fact be enchanced to include caching, we have a version that does this.  The default cqlrt doesn't include it because caching implies policy and cqlrt cannot know what the correct policy is, so we're silent on the matter.  But it's very easy to plug one in.  Messenger does.

**Comment by jackpal** [comment]
It might be worth having a "here's some things you will want to do to use this in production", document that covers stuff like this.

**Comment by ricomariani** [comment]
I think this is a good idea.  The thing is the stock cqlrt isn't that good.  For one thing it has threading issues.
________________________________

**Comment by ricomariani** [comment]
ok so I'm not going to do caching in the default but I will add notes to the CQLRT sections that explain what you probably want to replace.  And also I'll write a top level adopters guide that points you to these considerations.

**Comment by ricomariani** [comment]
https://github.com/facebookincubator/CG-SQL/pull/117

**Comment by ricomariani** [comment]
Notes on what you probably want to do have been added as appendix 11

https://cgsql.dev/cql-guide/x11/
