### ISSUE TITLE
demo.sh fails (CQL0435) on current release 

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#90]
Repro steps:

+ M1 Macbook Pro running MacOS 12.1
+ Install homebrew 3.0
+ Install flex, bison as directed by cg-sql docs
+ Build cgl app
+ cd sources/demo

```
$ ./demo.sh 
out/cql --in demo/demo.sql --cg out/demo.h out/demo.c
demo/demo.sql:55:1: error: in str : CQL0435: must use qualified form to avoid ambiguity with alias 'x'
demo/demo.sql:55:1: error: in str : CQL0435: must use qualified form to avoid ambiguity with alias 'x'
demo/demo.sql:55:1: error: in str : CQL0435: must use qualified form to avoid ambiguity with alias 'y'
demo/demo.sql:55:1: error: in str : CQL0435: must use qualified form to avoid ambiguity with alias 'y'
demo/demo.sql:55:1: error: in str : CQL0435: must use qualified form to avoid ambiguity with alias 'iter'
demo/demo.sql:66:1: error: in str : CQL0204: cursor not found 'C'
```

Changing demo.sql:55 to be this:

```
	 WHERE (m.x*m.x + m.y*m.y) < 4.0 AND m.iter<28
```
fixed all the errors.

**Comment by ricomariani** [comment]
We added CQL0435 a couple of weeks ago, we need to update the demo accordingly; No alias references.  I'll make a PR.

**Comment by ricomariani** [comment]
https://github.com/facebookincubator/CG-SQL/pull/93

**Comment by ricomariani** [comment]
As a point of interest, the real change is right here:

 WHERE m.x * m.x + m.y * m.y < 4.0 AND m.iter < 28),
 
 The rest is just formatting.
 
 Now the thing is, this is a good example of why the error was added.
 
 When it said
 
  WHERE x * x + y *y < 4.0 AND iter < 28),
  
  People might be astonished to discover that "iter" refers to m.iter as has been explicitly written rather than the aliased column name iter.  This is maybe less astonishing here because the example is so simple, but the meaning used to depend on whether or not "m" happened to have a column with the same name as the alias in which case that column takes priority.  That's a SQLite thing. This turns out to be very error-prone.

It's especially confusing when you are dealing with a recursion, like this case, where the value is updated so there are two versions of pretty much every column the before and after version.

**Comment by ricomariani** [comment]
Fix landed.
