### ISSUE TITLE
Suggestion: make the default versions of cql_log_database_error(...) and cql_error_trace() do something useful

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#96]
The default version of these cqlrt.h defines silently do nothing:

```
#define cql_log_database_error(...)
#define cql_error_trace()
```

I assume in production you have these log to your production logging system.

For teaching purposes, it would be good to have them print to stderr, something like:

```
#define cql_log_database_error(...) fprintf(stderr, ...)
#define cql_error_trace() do { fprintf(stderr,"cql_error_trace: %s:%d\n", __func__,__LINE__); } while(0);
```

(I'm not sure if cql_error_trace() is supposed to call cql_log_database_errror or not...)

**Comment by ricomariani** [comment]
The problem I always had with this was "what's useful".  Lots of scenarios this gets used in don't have any stderr... 

How do you feel about me meeting you half-way on this and I'll include default versions you can enable and mention it in the tutorial?  Fundamentally, cqlrt.c is designed to be replaced.  As your surmised, we have an entirely different one for iOS in the messenger environment.  If the trace macro is not empty there is a significant size cost.  But at FB we have a macro you can turn on that enables it if/when you need.  Usually it's turned on in just one or two files as needed but it never gets committed as "on".

**Comment by ricomariani** [comment]
>> (I'm not sure if cql_error_trace() is supposed to call cql_log_database_errror or not...)

It usually doesn't.

**Comment by ricomariani** [comment]
Some additional details:

`log_database_error` happens at the C/CQL boundary in `cql_code cql_fetch_all_results(...).`

When a result set is created that macro is used to log errors.  You define it as you see fit.  That one is much cheaper because the usage is shared.  cql_error_trace is sprinkled all over so that the error can be traced at the moment it is discovered before it might be lost.  The "cost" of having a centralized "log_database_error" in cqlrt_common.c is that by the time the error is logged it is very likely that several finalizations and so forth have happened.  These are necessary to not leak memory but since they succeeded SQLite's error message is gone, only the error code is left.  The only way to avoid that problem is to pay the cost of injecting the logging at every error check which is what the trace macro does.  But that cost is onerous.

**Comment by jackpal** [comment]
Makes sense. Thanks for explaining.

**Comment by jackpal** [comment]
By the way, I just noticed that there's a blog post that gives a good example implementation of the error cql_error_trace() macro:

https://cgsql.dev/blog/error-tracing-intro/
